### ISSUE TITLE
Add High Availability Guide to docs

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq.org#664] opened 2018-06-06 19:21 UTC
I can see the documentation in the [docs repo](https://github.com/ManageIQ/manageiq_docs/tree/master/doc-High_Availability_Guide/miq), but it doesn't appear on the website.

I'm not sure if this is an issue in the docs repo or here, so hoping someone could point me in the right direction.

**Comment by skateman** [comment] 2019-03-19 15:33
Well, I tried to build the documentation from its [repo](https://github.com/ManageIQ/manageiq_doc) and the asciibinder doesn't build the highavailability docs. So the problem is on the docs repo side, we're just consuming that.

I am just guessing, but the issue is probably with the [topic map](https://github.com/ManageIQ/manageiq_docs/blob/master/_topic_map.yml) file not containing any info about the high availability docs.

**Comment by Fryguy** [comment] 2020-04-07 17:51
Closed via https://github.com/ManageIQ/manageiq.org/pull/828

**Closed by Fryguy** 2020-04-07 17:51 UTC
Labels: enhancement, help wanted
